// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCeIhexOSdN8lWxAjRF_BCk5TD0FF8WNs',
    appId: '1:937068128406:web:2350ef84dbd6269951bab7',
    messagingSenderId: '937068128406',
    projectId: 'roadassist-90f40',
    authDomain: 'roadassist-90f40.firebaseapp.com',
    storageBucket: 'roadassist-90f40.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPLM3vFwudMxMg5T5yLE-s65lo2h0_Hcc',
    appId: '1:937068128406:android:6dd4814f94c6bf8551bab7',
    messagingSenderId: '937068128406',
    projectId: 'roadassist-90f40',
    storageBucket: 'roadassist-90f40.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2RmvKN7eNpL_u8aQzQxvT7Xn6QZKDUQE',
    appId: '1:937068128406:ios:392613eda707b5c151bab7',
    messagingSenderId: '937068128406',
    projectId: 'roadassist-90f40',
    storageBucket: 'roadassist-90f40.firebasestorage.app',
    iosBundleId: 'com.example.roadAssist',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2RmvKN7eNpL_u8aQzQxvT7Xn6QZKDUQE',
    appId: '1:937068128406:ios:392613eda707b5c151bab7',
    messagingSenderId: '937068128406',
    projectId: 'roadassist-90f40',
    storageBucket: 'roadassist-90f40.firebasestorage.app',
    iosBundleId: 'com.example.roadAssist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCeIhexOSdN8lWxAjRF_BCk5TD0FF8WNs',
    appId: '1:937068128406:web:096e9c7619f52a3d51bab7',
    messagingSenderId: '937068128406',
    projectId: 'roadassist-90f40',
    authDomain: 'roadassist-90f40.firebaseapp.com',
    storageBucket: 'roadassist-90f40.firebasestorage.app',
  );
}
