// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD691BByqeCs9eynWq5chFdyMhiZ4vZpbU',
    appId: '1:642950415530:web:829f975dda37c81ff6fcd3',
    messagingSenderId: '642950415530',
    projectId: 'roadassist-f1081',
    authDomain: 'roadassist-f1081.firebaseapp.com',
    storageBucket: 'roadassist-f1081.firebasestorage.app',
    measurementId: 'G-NNSXTLFTVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMi86rIU-Me3Y_Y6sXM40JhUsKCeqbt3k',
    appId: '1:642950415530:android:8b8bd3c0bd7bf61af6fcd3',
    messagingSenderId: '642950415530',
    projectId: 'roadassist-f1081',
    storageBucket: 'roadassist-f1081.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCktEPAc4WGxzLhL3RrhksPEQO4zC26kCo',
    appId: '1:642950415530:ios:fa8e8740791f3136f6fcd3',
    messagingSenderId: '642950415530',
    projectId: 'roadassist-f1081',
    storageBucket: 'roadassist-f1081.firebasestorage.app',
    iosBundleId: 'com.example.roadAssist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCktEPAc4WGxzLhL3RrhksPEQO4zC26kCo',
    appId: '1:642950415530:ios:fa8e8740791f3136f6fcd3',
    messagingSenderId: '642950415530',
    projectId: 'roadassist-f1081',
    storageBucket: 'roadassist-f1081.firebasestorage.app',
    iosBundleId: 'com.example.roadAssist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD691BByqeCs9eynWq5chFdyMhiZ4vZpbU',
    appId: '1:642950415530:web:f02b91234e983ec6f6fcd3',
    messagingSenderId: '642950415530',
    projectId: 'roadassist-f1081',
    authDomain: 'roadassist-f1081.firebaseapp.com',
    storageBucket: 'roadassist-f1081.firebasestorage.app',
    measurementId: 'G-SH79JG419N',
  );
}
